version: '3'
services:

  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=development
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    working_dir: '/app'
    command: ["rails", "s", "-b", "0.0.0.0"]
    volumes:
      - .:/app  
      - gems_cache:/usr/local/bundle
      - node_modules_cache:/app/node_modules
    depends_on:
      - db    

volumes:
  db_data:
  gems_cache:
  node_modules_cache:
